/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Generar_Grafica;
import Clases.ValidarPalabra;
import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mynor
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        alfabeto = new ArrayList<>();
        graf = new Generar_Grafica();
        validar = new ValidarPalabra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtExpresion = new javax.swing.JTextField();
        btnIngresarPalabra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAlfabeto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTPalabras = new rojerusan.RSTableMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGrafico = new javax.swing.JPanel();
        lblGrafico = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnGraficar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        rSLabelVerticalD1 = new rojerusan.RSLabelVerticalD();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/13297.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1230, 10, 40, 40);

        jLabel2.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autómata Finito No Determinista");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 10, 440, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_portal.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 220, 90);

        txtExpresion.setBackground(new java.awt.Color(255, 255, 255));
        txtExpresion.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        txtExpresion.setForeground(new java.awt.Color(0, 102, 102));
        txtExpresion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtExpresion.setOpaque(true);
        txtExpresion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExpresionKeyTyped(evt);
            }
        });
        jPanel1.add(txtExpresion);
        txtExpresion.setBounds(10, 520, 500, 40);

        btnIngresarPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkmark.png"))); // NOI18N
        btnIngresarPalabra.setBorderPainted(false);
        btnIngresarPalabra.setContentAreaFilled(false);
        btnIngresarPalabra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarPalabra.setEnabled(false);
        btnIngresarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPalabraActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarPalabra);
        btnIngresarPalabra.setBounds(760, 560, 60, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Alfabeto.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 70, 40);

        lblAlfabeto.setBackground(new java.awt.Color(0, 0, 0));
        lblAlfabeto.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        lblAlfabeto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblAlfabeto);
        lblAlfabeto.setBounds(90, 90, 1080, 40);

        jScrollPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setOpaque(true);

        JTPalabras.setBackground(new java.awt.Color(0, 102, 102));
        JTPalabras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTPalabras.setForeground(new java.awt.Color(255, 255, 255));
        JTPalabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra", "Válido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTPalabras.setAltoHead(60);
        JTPalabras.setColorBackgoundHead(new java.awt.Color(0, 102, 102));
        JTPalabras.setColorFilasBackgound2(new java.awt.Color(0, 102, 102));
        JTPalabras.setColorFilasForeground1(new java.awt.Color(0, 102, 102));
        JTPalabras.setColorFilasForeground2(new java.awt.Color(255, 255, 255));
        JTPalabras.setColumnSelectionAllowed(true);
        JTPalabras.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        JTPalabras.setFuenteFilas(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        JTPalabras.setFuenteHead(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jScrollPane3.setViewportView(JTPalabras);
        JTPalabras.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (JTPalabras.getColumnModel().getColumnCount() > 0) {
            JTPalabras.getColumnModel().getColumn(0).setResizable(false);
            JTPalabras.getColumnModel().getColumn(1).setMinWidth(150);
            JTPalabras.getColumnModel().getColumn(1).setPreferredWidth(150);
            JTPalabras.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(810, 130, 470, 350);

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelGrafico.setBackground(new java.awt.Color(0, 102, 102));
        panelGrafico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGrafico.add(lblGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 350));

        jScrollPane1.setViewportView(panelGrafico);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 740, 360);

        jLabel5.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Expresión Regular");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 480, 670, 40);

        jLabel7.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Palabra");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(760, 480, 320, 40);

        txtPalabra.setEditable(false);
        txtPalabra.setBackground(new java.awt.Color(255, 255, 255));
        txtPalabra.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        txtPalabra.setForeground(new java.awt.Color(0, 102, 102));
        txtPalabra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPalabra.setOpaque(true);
        txtPalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPalabraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPalabraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPalabra);
        txtPalabra.setBounds(760, 520, 520, 40);

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checkmark.png"))); // NOI18N
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(0, 560, 60, 50);

        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reload.png"))); // NOI18N
        btnGraficar.setBorderPainted(false);
        btnGraficar.setContentAreaFilled(false);
        btnGraficar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGraficar.setEnabled(false);
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGraficar);
        btnGraficar.setBounds(750, 410, 60, 50);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clear.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(80, 560, 60, 50);

        rSLabelVerticalD1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelVerticalD1.setText("Gráficar ------------->");
        rSLabelVerticalD1.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jPanel1.add(rSLabelVerticalD1);
        rSLabelVerticalD1.setBounds(760, 130, 40, 280);

        jLabel6.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Expresiones Regulares");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 40, 410, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpresionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpresionKeyTyped
        char c = evt.getKeyChar();
        if (c >= 'A' && c <= 'Z') {
            evt.consume();
        } else if ((c != '|' && c != '(' && c != ')' && c != '*') && !(c >= 'a' && c <= 'z') && !(c >= '0' && c <= '9')) {
            evt.consume();
        }

    }//GEN-LAST:event_txtExpresionKeyTyped

    private boolean verificar() {
        cad = txtExpresion.getText().toCharArray();
        boolean errores = false;
        for (int i = 0; i < cad.length; i++) {
            if (cad[0] == '*' || cad[0] == '|' || cad[0]==')') {
                errores = true;
            } else {
                switch (cad[i]) {
                    case '(':
                        cont += 1;
                        if (cad[i+1] == '*' || cad[i+1] == '|'){
                            errores=true;
                        }
                        break;
                    case ')':
                        if(i+1==cad.length){
                            if(cad[i]=='|')
                                errores=true;
                        }
                        cont -= 1;
                        break;
                    default:
                        if (cad[i] != '*' && cad[i] != '|') {
                            if (alfabeto.isEmpty()) {
                                alfabeto.add("" + cad[i]);
                            } else {
                                if(i+1==cad.length && cad[i]=='|'){
                                    errores=true;
                                }else{
                                    if(cad[i]=='|'){
                                        if(cad[i+1]=='*'||cad[i]==')'){
                                            errores=true;
                                        }
                                    }
                                }
                                boolean encontrado = false;
                                for (String alfabeto1 : alfabeto) {
                                    if (alfabeto1.equals("" + cad[i])) {
                                        encontrado = true;
                                    }
                                }
                                if (!encontrado) {
                                    alfabeto.add("" + cad[i]);
                                }
                            }
                        }
                        break;
                }
            }
        }
        if (cont == 0 && !errores) {
            String texto = "{ ";
            Collections.sort(alfabeto);
            texto = alfabeto.stream().map((alf) -> alf).reduce(texto, String::concat);
            texto += " }";
            lblAlfabeto.setText(texto);
            txtExpresion.setEditable(false);
            btnIngresar.setEnabled(false);
            btnIngresarPalabra.setEnabled(true);
            txtPalabra.setEditable(true);
            return true;
        } else {
            cont = 0;
            JOptionPane.showMessageDialog(null, "Expresión regular incorrecta");
            return false;
        }
    }

    private void verificarEK(char[] cad) {
        String aux1 = "";
        int j = -1;
        boolean encontrado = false;
        for (int i = 0; i < cad.length; i++) {
            if (cad[i] == '(' && !encontrado) {
                j = i;
                parentesis = true;
                aux1 += cad[i];
                while (j < cad.length && !encontrado) {
                    if (cad[j] == ')' && j + 1 != cad.length) {
                        if (cad[j + 1] == '*') {
                            encontrado = true;
                        }
                    }
                    j++;
                }
            } else {
                if (j != i) {
                    aux1 += cad[i];
                } else {
                    encontrado = false;
                }
            }
            if (encontrado) {
                if (cad[i] != '(' && cad[i] != ')' && cad[i] != '|' && j != i) {
                    aux1 += "*";
                }
            }
        }
        System.out.println(aux1);
        this.cad = aux1.toCharArray();
    }
    private void btnIngresarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPalabraActionPerformed
        Buscar();
    }//GEN-LAST:event_btnIngresarPalabraActionPerformed

    private void Buscar() {
        char[] cadena = txtPalabra.getText().toCharArray();

        if (validar.Buscar(cadena)) {
            JTPalabras.setModel(llenartablabla("Si"));
        } else {
            JTPalabras.setModel(llenartablabla("No"));
        }
    }

    private DefaultTableModel llenartablabla(String valido) {
        DefaultTableModel modelo = (DefaultTableModel) JTPalabras.getModel();
        String[] cadena = new String[2];
        cadena[0] = txtPalabra.getText();
        cadena[1] = valido;
        modelo.addRow(cadena);
        return modelo;
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void txtPalabraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabraKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtExpresion.getText().length() != 0) {
            if (verificar()) {
                if (graf.SetER(txtExpresion.getText())) {
                    btnGraficar.setEnabled(true);
                    verificarEK(cad);
                    if (parentesis) {
                        validar.insertarConParentesis(cad);
                    } else {
                        validar.insertarSinParentesis(cad);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "El campo \"expresión regular\" está vacío.");
            txtExpresion.requestFocus();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        ImageIcon imagen = new ImageIcon("Automata.jpg");
        imagen.getImage().flush();
        lblGrafico.setIcon(imagen);
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtPalabraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPalabraKeyPressed
        if (evt.getKeyChar() == 10) {
            Buscar();
        }
    }//GEN-LAST:event_txtPalabraKeyPressed

    private void Limpiar() {
        lblAlfabeto.setText("");
        txtExpresion.setEditable(true);
        txtExpresion.setText("");
        txtExpresion.requestFocus();
        txtPalabra.setText("");
        alfabeto = new ArrayList<>();
        cont = 0;
        validar = new ValidarPalabra();
        parentesis = false;
        btnIngresar.setEnabled(true);
        btnIngresarPalabra.setEnabled(false);
        DefaultTableModel modelo = (DefaultTableModel) JTPalabras.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    private ArrayList<String> alfabeto;
    private int cont = 0;
    private char cad[];
    private int x, y;
    private final Generar_Grafica graf;
    private ValidarPalabra validar;
    private boolean parentesis = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro JTPalabras;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresarPalabra;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlfabeto;
    private javax.swing.JLabel lblGrafico;
    private javax.swing.JPanel panelGrafico;
    private rojerusan.RSLabelVerticalD rSLabelVerticalD1;
    private javax.swing.JTextField txtExpresion;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
